// <auto-generated />
using System;
using GameStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameStore.Data.Migrations
{
    [DbContext(typeof(GameStoreDbContext))]
    [Migration("20231007100011_AddedGenreEntity")]
    partial class AddedGenreEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameStore.Data.Entities.Game", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("GenreId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Alias")
                        .IsUnique();

                    b.HasIndex("GenreId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Alias = "zelda-breath-of-the-wild",
                            Description = "An action-adventure game in an open world.",
                            GenreId = 14L,
                            Name = "The Legend of Zelda: Breath of the Wild"
                        },
                        new
                        {
                            Id = 2L,
                            Alias = "gta-v",
                            Description = "An open-world action-adventure game.",
                            GenreId = 11L,
                            Name = "Grand Theft Auto V"
                        });
                });

            modelBuilder.Entity("GameStore.Data.Entities.Genre", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long?>("ParentGenreId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentGenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Name = "Strategy"
                        },
                        new
                        {
                            Id = 2L,
                            Name = "RTS",
                            ParentGenreId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            Name = "TBS",
                            ParentGenreId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            Name = "RPG"
                        },
                        new
                        {
                            Id = 5L,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 6L,
                            Name = "Races"
                        },
                        new
                        {
                            Id = 7L,
                            Name = "Rally",
                            ParentGenreId = 6L
                        },
                        new
                        {
                            Id = 8L,
                            Name = "Arcade",
                            ParentGenreId = 6L
                        },
                        new
                        {
                            Id = 9L,
                            Name = "Formula",
                            ParentGenreId = 6L
                        },
                        new
                        {
                            Id = 10L,
                            Name = "Off-road",
                            ParentGenreId = 6L
                        },
                        new
                        {
                            Id = 11L,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 12L,
                            Name = "FPS",
                            ParentGenreId = 11L
                        },
                        new
                        {
                            Id = 13L,
                            Name = "TPS",
                            ParentGenreId = 11L
                        },
                        new
                        {
                            Id = 14L,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 15L,
                            Name = "Puzzle & Skill"
                        },
                        new
                        {
                            Id = 16L,
                            Name = "Misc."
                        });
                });

            modelBuilder.Entity("GameStore.Data.Entities.Game", b =>
                {
                    b.HasOne("GameStore.Data.Entities.Genre", "Genre")
                        .WithMany("Games")
                        .HasForeignKey("GenreId");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("GameStore.Data.Entities.Genre", b =>
                {
                    b.HasOne("GameStore.Data.Entities.Genre", null)
                        .WithMany("SubGenres")
                        .HasForeignKey("ParentGenreId");
                });

            modelBuilder.Entity("GameStore.Data.Entities.Genre", b =>
                {
                    b.Navigation("Games");

                    b.Navigation("SubGenres");
                });
#pragma warning restore 612, 618
        }
    }
}
