// <auto-generated />
using System;
using GameStore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameStore.Data.Migrations
{
    [DbContext(typeof(GameStoreDbContext))]
    [Migration("20231227130400_PermissionsFix")]
    partial class PermissionsFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameStore.Data.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Intro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.HasIndex("ParentId");

                    b.ToTable("Comment");
                });

            modelBuilder.Entity("GameStore.Data.Entities.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Deleted")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Discontinued")
                        .HasColumnType("bit");

                    b.Property<string>("LegacyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PageViews")
                        .HasColumnType("decimal(20,0)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<DateTime?>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PublisherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("UnitInStock")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("Alias")
                        .IsUnique();

                    b.HasIndex("PublisherId");

                    b.ToTable("Game");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8e9d1000-50e0-4bd8-8159-42c7431f32b5"),
                            Alias = "zelda-breath-of-the-wild",
                            CreationDate = new DateTime(2023, 10, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Description = "An action-adventure game in an open world.",
                            Discontinued = false,
                            Name = "The Legend of Zelda: Breath of the Wild",
                            PageViews = 0m,
                            Price = 1500.2m,
                            PublishDate = new DateTime(2017, 4, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = new Guid("defd4ed1-a967-48af-83fb-4e5ffee412b0"),
                            UnitInStock = (short)50
                        },
                        new
                        {
                            Id = new Guid("95ffb14c-267a-432a-9d7c-22f887290d49"),
                            Alias = "gta-v",
                            CreationDate = new DateTime(2023, 10, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Description = "An open-world action-adventure game.",
                            Discontinued = true,
                            Name = "Grand Theft Auto V",
                            PageViews = 0m,
                            Price = 500m,
                            PublishDate = new DateTime(2013, 9, 17, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = new Guid("ec62c5de-e415-4e74-bc75-3a7606563c78"),
                            UnitInStock = (short)32
                        },
                        new
                        {
                            Id = new Guid("e2e928c4-ab49-4bc0-a904-37c34e1385cc"),
                            Alias = "overwatch-2",
                            CreationDate = new DateTime(2023, 10, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Description = "Overwatch 2 is a free-to-play, team-based action game.",
                            Discontinued = false,
                            Name = "Overwatch 2",
                            PageViews = 0m,
                            Price = 1200m,
                            PublishDate = new DateTime(2022, 10, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = new Guid("3f8fc430-d0a5-4779-a3a4-5e0add54fde6"),
                            UnitInStock = (short)20
                        },
                        new
                        {
                            Id = new Guid("4b5f1e22-cd59-4523-a4e9-f0c0239ab820"),
                            Alias = "hearthstone",
                            CreationDate = new DateTime(2023, 10, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Description = "Hearthstone is a fast-paced strategy card game from Blizzard Entertainment.",
                            Discontinued = false,
                            Name = "Hearthstone",
                            PageViews = 0m,
                            Price = 800m,
                            PublishDate = new DateTime(2014, 4, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = new Guid("3f8fc430-d0a5-4779-a3a4-5e0add54fde6"),
                            UnitInStock = (short)45
                        },
                        new
                        {
                            Id = new Guid("352997f0-9cb6-4951-8b55-10df09d2e168"),
                            Alias = "star-wars-jedi",
                            CreationDate = new DateTime(2023, 10, 24, 0, 0, 0, 0, DateTimeKind.Utc),
                            Deleted = false,
                            Description = "A 3rd person action-adventure title from Respawn.",
                            Discontinued = false,
                            Name = "Star Wars Jedi: Fallen Order",
                            PageViews = 0m,
                            Price = 1400m,
                            PublishDate = new DateTime(2019, 9, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            PublisherId = new Guid("08029ea0-8bd8-494c-b3c5-b65a61538f81"),
                            UnitInStock = (short)34
                        });
                });

            modelBuilder.Entity("GameStore.Data.Entities.GameGenre", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GenreId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GameId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("GameGenre");

                    b.HasData(
                        new
                        {
                            GameId = new Guid("8e9d1000-50e0-4bd8-8159-42c7431f32b5"),
                            GenreId = new Guid("dd2bf352-9cfd-4b88-b46f-08217104f90d")
                        },
                        new
                        {
                            GameId = new Guid("8e9d1000-50e0-4bd8-8159-42c7431f32b5"),
                            GenreId = new Guid("e96511b9-e864-44cc-899f-8313609ffb63")
                        },
                        new
                        {
                            GameId = new Guid("95ffb14c-267a-432a-9d7c-22f887290d49"),
                            GenreId = new Guid("e96511b9-e864-44cc-899f-8313609ffb63")
                        },
                        new
                        {
                            GameId = new Guid("e2e928c4-ab49-4bc0-a904-37c34e1385cc"),
                            GenreId = new Guid("e96511b9-e864-44cc-899f-8313609ffb63")
                        },
                        new
                        {
                            GameId = new Guid("e2e928c4-ab49-4bc0-a904-37c34e1385cc"),
                            GenreId = new Guid("f82e27c8-760e-4cb8-866f-60bb33caeaac")
                        },
                        new
                        {
                            GameId = new Guid("4b5f1e22-cd59-4523-a4e9-f0c0239ab820"),
                            GenreId = new Guid("073f790e-a105-491d-965c-946e841c3b3e")
                        },
                        new
                        {
                            GameId = new Guid("4b5f1e22-cd59-4523-a4e9-f0c0239ab820"),
                            GenreId = new Guid("d9eaef23-9680-4d25-869b-4ed91847fd03")
                        },
                        new
                        {
                            GameId = new Guid("352997f0-9cb6-4951-8b55-10df09d2e168"),
                            GenreId = new Guid("e96511b9-e864-44cc-899f-8313609ffb63")
                        },
                        new
                        {
                            GameId = new Guid("352997f0-9cb6-4951-8b55-10df09d2e168"),
                            GenreId = new Guid("dd2bf352-9cfd-4b88-b46f-08217104f90d")
                        });
                });

            modelBuilder.Entity("GameStore.Data.Entities.GamePlatform", b =>
                {
                    b.Property<Guid>("GameId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PlatformId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GameId", "PlatformId");

                    b.HasIndex("PlatformId");

                    b.ToTable("GamePlatform");

                    b.HasData(
                        new
                        {
                            GameId = new Guid("8e9d1000-50e0-4bd8-8159-42c7431f32b5"),
                            PlatformId = new Guid("83262eb9-517e-4581-b7ba-88b57c33d721")
                        },
                        new
                        {
                            GameId = new Guid("95ffb14c-267a-432a-9d7c-22f887290d49"),
                            PlatformId = new Guid("4adb2c38-f819-43cd-aa78-f46d482ceeb7")
                        },
                        new
                        {
                            GameId = new Guid("95ffb14c-267a-432a-9d7c-22f887290d49"),
                            PlatformId = new Guid("83262eb9-517e-4581-b7ba-88b57c33d721")
                        },
                        new
                        {
                            GameId = new Guid("e2e928c4-ab49-4bc0-a904-37c34e1385cc"),
                            PlatformId = new Guid("4adb2c38-f819-43cd-aa78-f46d482ceeb7")
                        },
                        new
                        {
                            GameId = new Guid("e2e928c4-ab49-4bc0-a904-37c34e1385cc"),
                            PlatformId = new Guid("83262eb9-517e-4581-b7ba-88b57c33d721")
                        },
                        new
                        {
                            GameId = new Guid("4b5f1e22-cd59-4523-a4e9-f0c0239ab820"),
                            PlatformId = new Guid("a9f806b4-28c5-4d7b-a776-65dfe029de8f")
                        },
                        new
                        {
                            GameId = new Guid("4b5f1e22-cd59-4523-a4e9-f0c0239ab820"),
                            PlatformId = new Guid("467762c6-8a10-4570-b829-e29de78a0757")
                        },
                        new
                        {
                            GameId = new Guid("4b5f1e22-cd59-4523-a4e9-f0c0239ab820"),
                            PlatformId = new Guid("4adb2c38-f819-43cd-aa78-f46d482ceeb7")
                        },
                        new
                        {
                            GameId = new Guid("352997f0-9cb6-4951-8b55-10df09d2e168"),
                            PlatformId = new Guid("467762c6-8a10-4570-b829-e29de78a0757")
                        },
                        new
                        {
                            GameId = new Guid("352997f0-9cb6-4951-8b55-10df09d2e168"),
                            PlatformId = new Guid("4adb2c38-f819-43cd-aa78-f46d482ceeb7")
                        },
                        new
                        {
                            GameId = new Guid("352997f0-9cb6-4951-8b55-10df09d2e168"),
                            PlatformId = new Guid("83262eb9-517e-4581-b7ba-88b57c33d721")
                        });
                });

            modelBuilder.Entity("GameStore.Data.Entities.Genre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LegacyId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("ParentGenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ParentGenreId");

                    b.ToTable("Genre");

                    b.HasData(
                        new
                        {
                            Id = new Guid("073f790e-a105-491d-965c-946e841c3b3e"),
                            Name = "Strategy"
                        },
                        new
                        {
                            Id = new Guid("04b04522-e758-4f8c-b58f-f59dd8de54b5"),
                            Name = "RTS",
                            ParentGenreId = new Guid("073f790e-a105-491d-965c-946e841c3b3e")
                        },
                        new
                        {
                            Id = new Guid("ead8a2bf-e751-47a9-a2fc-e8b6f643b0c8"),
                            Name = "TBS",
                            ParentGenreId = new Guid("073f790e-a105-491d-965c-946e841c3b3e")
                        },
                        new
                        {
                            Id = new Guid("5efe1909-c0b0-440e-8915-2831570816ec"),
                            Name = "RPG"
                        },
                        new
                        {
                            Id = new Guid("13ba20d2-42fc-4eaa-a7f9-900782cabfc3"),
                            Name = "Sports"
                        },
                        new
                        {
                            Id = new Guid("b3562f18-5e7c-411a-ab76-b675b78bd23d"),
                            Name = "Races"
                        },
                        new
                        {
                            Id = new Guid("2ba0604c-5515-470c-a500-58b60e8be000"),
                            Name = "Rally",
                            ParentGenreId = new Guid("b3562f18-5e7c-411a-ab76-b675b78bd23d")
                        },
                        new
                        {
                            Id = new Guid("e0e725ed-50ed-4ff7-94e7-38d0e1d2fa39"),
                            Name = "Arcade",
                            ParentGenreId = new Guid("b3562f18-5e7c-411a-ab76-b675b78bd23d")
                        },
                        new
                        {
                            Id = new Guid("927cc631-c4f1-4feb-8a0c-9db6cd43402a"),
                            Name = "Formula",
                            ParentGenreId = new Guid("b3562f18-5e7c-411a-ab76-b675b78bd23d")
                        },
                        new
                        {
                            Id = new Guid("5d7545f5-a77a-4632-89c6-40f8756d2f75"),
                            Name = "Off-road",
                            ParentGenreId = new Guid("b3562f18-5e7c-411a-ab76-b675b78bd23d")
                        },
                        new
                        {
                            Id = new Guid("e96511b9-e864-44cc-899f-8313609ffb63"),
                            Name = "Action"
                        },
                        new
                        {
                            Id = new Guid("f82e27c8-760e-4cb8-866f-60bb33caeaac"),
                            Name = "FPS",
                            ParentGenreId = new Guid("e96511b9-e864-44cc-899f-8313609ffb63")
                        },
                        new
                        {
                            Id = new Guid("837e2c69-c602-4038-9754-47b9c005a0a8"),
                            Name = "TPS",
                            ParentGenreId = new Guid("e96511b9-e864-44cc-899f-8313609ffb63")
                        },
                        new
                        {
                            Id = new Guid("dd2bf352-9cfd-4b88-b46f-08217104f90d"),
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = new Guid("d9eaef23-9680-4d25-869b-4ed91847fd03"),
                            Name = "Puzzle & Skill"
                        },
                        new
                        {
                            Id = new Guid("956c4baf-e989-4046-b6cb-1d98df33cf6d"),
                            Name = "Misc."
                        });
                });

            modelBuilder.Entity("GameStore.Data.Entities.Identity.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "45083adf-a7ca-4576-a374-d9a072ef0bda",
                            ConcurrencyStamp = "b149eec2-f18e-4acb-8c4c-4bb0e4c82e8b",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "80e3704c-7e3d-48f3-bb14-dd8e996daa59",
                            ConcurrencyStamp = "bcec8e70-4b32-4ee1-b74e-5c555013aa29",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = "b17220dc-9059-4daa-8048-af443aa08a78",
                            ConcurrencyStamp = "146b7446-fe49-40bf-9bbb-f1cb2fcc039e",
                            Name = "Moderator",
                            NormalizedName = "MODERATOR"
                        },
                        new
                        {
                            Id = "7a44e3b0-3baf-4831-8362-1a32f7460051",
                            ConcurrencyStamp = "2cdbf1d1-f008-4fb5-a2cb-11b621d44a71",
                            Name = "Publisher",
                            NormalizedName = "PUBLISHER"
                        },
                        new
                        {
                            Id = "d18422a3-6a29-44e9-88b2-774db642bf6d",
                            ConcurrencyStamp = "2581396a-ec75-4c4a-b90d-f7de670455ac",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("GameStore.Data.Entities.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "91193760-0bd1-4eac-92f8-0bd8b4ac2c6a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "949d2829-0c95-4e3c-812f-d48093a7c7fd",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAEL85uhHv75LYDizv0bc7p+eb0vNckMJiQ+6FkT1pntP/xm7CLDweHcd3s7p3Z8f1fg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f68dad0e-f850-4969-a4a3-b513064cb38f",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("GameStore.Data.Entities.Identity.ApplicationUserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "91193760-0bd1-4eac-92f8-0bd8b4ac2c6a",
                            RoleId = "45083adf-a7ca-4576-a374-d9a072ef0bda"
                        });
                });

            modelBuilder.Entity("GameStore.Data.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("PaymentMethodId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ShippedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Sum")
                        .HasColumnType("money");

                    b.HasKey("Id");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("GameStore.Data.Entities.OrderDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("Discount")
                        .HasColumnType("real");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("Quantity")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("GameStore.Data.Entities.PaymentMethod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("PaymentMethod");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77301abc-0738-4540-aa3a-19db9f6bc2dc"),
                            Description = "Use a bank of your choice to make payments!",
                            ImageUrl = "https://static.vecteezy.com/system/resources/thumbnails/000/594/232/small/B001.jpg",
                            Title = "Bank"
                        },
                        new
                        {
                            Id = new Guid("32bda162-d288-4a60-a684-9bd7caf61951"),
                            Description = "Simply pay with IBox!",
                            ImageUrl = "https://logowik.com/content/uploads/images/ibox9043.logowik.com.webp",
                            Title = "IBox terminal"
                        },
                        new
                        {
                            Id = new Guid("d84def54-1f51-4f1d-aedc-fc1d18b4fa12"),
                            Description = "Pay with your favourite card!",
                            ImageUrl = "https://d1yjjnpx0p53s8.cloudfront.net/styles/logo-thumbnail/s3/0013/4323/brand.gif?itok=fSmoZrGH",
                            Title = "Visa"
                        });
                });

            modelBuilder.Entity("GameStore.Data.Entities.Platform", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("Platform");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a9f806b4-28c5-4d7b-a776-65dfe029de8f"),
                            Type = "mobile"
                        },
                        new
                        {
                            Id = new Guid("467762c6-8a10-4570-b829-e29de78a0757"),
                            Type = "cloud"
                        },
                        new
                        {
                            Id = new Guid("4adb2c38-f819-43cd-aa78-f46d482ceeb7"),
                            Type = "desktop"
                        },
                        new
                        {
                            Id = new Guid("83262eb9-517e-4581-b7ba-88b57c33d721"),
                            Type = "console"
                        });
                });

            modelBuilder.Entity("GameStore.Data.Entities.Publisher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.Property<string>("HomePage")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.Property<string>("LegacyId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasFilter("[AccountId] IS NOT NULL");

                    b.HasIndex("CompanyName")
                        .IsUnique();

                    b.ToTable("Publisher");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3f8fc430-d0a5-4779-a3a4-5e0add54fde6"),
                            CompanyName = "Activision",
                            Description = "Activision Publishing, Inc. is an American video game publisher based in Santa Monica, California.",
                            HomePage = "https://www.activision.com/"
                        },
                        new
                        {
                            Id = new Guid("08029ea0-8bd8-494c-b3c5-b65a61538f81"),
                            CompanyName = "Electronic Arts",
                            Description = "Electronic Arts Inc. is a global leader in digital interactive entertainment.",
                            HomePage = "https://www.ea.com/"
                        },
                        new
                        {
                            Id = new Guid("97fd0c5c-0504-4687-9a36-a65e699ca393"),
                            CompanyName = "Ubisoft",
                            Description = "Ubisoft Entertainment SA is a French video game company headquartered in Montreal.",
                            HomePage = "https://www.ubisoft.com/"
                        },
                        new
                        {
                            Id = new Guid("defd4ed1-a967-48af-83fb-4e5ffee412b0"),
                            CompanyName = "Nintendo",
                            Description = "Nintendo Co., Ltd.[b] is a Japanese multinational video game company headquartered in Kyoto.",
                            HomePage = "https://www.nintendo.com/"
                        },
                        new
                        {
                            Id = new Guid("ec62c5de-e415-4e74-bc75-3a7606563c78"),
                            CompanyName = "Rockstar Games",
                            Description = "Rockstar Games, Inc. is an American video game publisher based in New York City.",
                            HomePage = "https://www.rockstargames.com/"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimType = "permission",
                            ClaimValue = "user:full",
                            RoleId = "45083adf-a7ca-4576-a374-d9a072ef0bda"
                        },
                        new
                        {
                            Id = 2,
                            ClaimType = "permission",
                            ClaimValue = "role:full",
                            RoleId = "45083adf-a7ca-4576-a374-d9a072ef0bda"
                        },
                        new
                        {
                            Id = 3,
                            ClaimType = "permission",
                            ClaimValue = "game:full",
                            RoleId = "45083adf-a7ca-4576-a374-d9a072ef0bda"
                        },
                        new
                        {
                            Id = 4,
                            ClaimType = "permission",
                            ClaimValue = "genre:full",
                            RoleId = "45083adf-a7ca-4576-a374-d9a072ef0bda"
                        },
                        new
                        {
                            Id = 5,
                            ClaimType = "permission",
                            ClaimValue = "publisher:full",
                            RoleId = "45083adf-a7ca-4576-a374-d9a072ef0bda"
                        },
                        new
                        {
                            Id = 6,
                            ClaimType = "permission",
                            ClaimValue = "platform:full",
                            RoleId = "45083adf-a7ca-4576-a374-d9a072ef0bda"
                        },
                        new
                        {
                            Id = 7,
                            ClaimType = "permission",
                            ClaimValue = "comment:full",
                            RoleId = "45083adf-a7ca-4576-a374-d9a072ef0bda"
                        },
                        new
                        {
                            Id = 8,
                            ClaimType = "permission",
                            ClaimValue = "order:full",
                            RoleId = "45083adf-a7ca-4576-a374-d9a072ef0bda"
                        },
                        new
                        {
                            Id = 10,
                            ClaimType = "permission",
                            ClaimValue = "game:view-deleted",
                            RoleId = "80e3704c-7e3d-48f3-bb14-dd8e996daa59"
                        },
                        new
                        {
                            Id = 11,
                            ClaimType = "permission",
                            ClaimValue = "game:create",
                            RoleId = "80e3704c-7e3d-48f3-bb14-dd8e996daa59"
                        },
                        new
                        {
                            Id = 12,
                            ClaimType = "permission",
                            ClaimValue = "game:update",
                            RoleId = "80e3704c-7e3d-48f3-bb14-dd8e996daa59"
                        },
                        new
                        {
                            Id = 13,
                            ClaimType = "permission",
                            ClaimValue = "game:delete",
                            RoleId = "80e3704c-7e3d-48f3-bb14-dd8e996daa59"
                        },
                        new
                        {
                            Id = 14,
                            ClaimType = "permission",
                            ClaimValue = "genre:full",
                            RoleId = "80e3704c-7e3d-48f3-bb14-dd8e996daa59"
                        },
                        new
                        {
                            Id = 15,
                            ClaimType = "permission",
                            ClaimValue = "publisher:full",
                            RoleId = "80e3704c-7e3d-48f3-bb14-dd8e996daa59"
                        },
                        new
                        {
                            Id = 16,
                            ClaimType = "permission",
                            ClaimValue = "platform:full",
                            RoleId = "80e3704c-7e3d-48f3-bb14-dd8e996daa59"
                        },
                        new
                        {
                            Id = 17,
                            ClaimType = "permission",
                            ClaimValue = "order:view-history",
                            RoleId = "80e3704c-7e3d-48f3-bb14-dd8e996daa59"
                        },
                        new
                        {
                            Id = 18,
                            ClaimType = "permission",
                            ClaimValue = "order:update",
                            RoleId = "80e3704c-7e3d-48f3-bb14-dd8e996daa59"
                        },
                        new
                        {
                            Id = 21,
                            ClaimType = "permission",
                            ClaimValue = "game:view-deleted",
                            RoleId = "b17220dc-9059-4daa-8048-af443aa08a78"
                        },
                        new
                        {
                            Id = 25,
                            ClaimType = "permission",
                            ClaimValue = "comment:full",
                            RoleId = "b17220dc-9059-4daa-8048-af443aa08a78"
                        },
                        new
                        {
                            Id = 29,
                            ClaimType = "permission",
                            ClaimValue = "publisher:update-self",
                            RoleId = "7a44e3b0-3baf-4831-8362-1a32f7460051"
                        },
                        new
                        {
                            Id = 30,
                            ClaimType = "permission",
                            ClaimValue = "game:update-own",
                            RoleId = "7a44e3b0-3baf-4831-8362-1a32f7460051"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("GameStore.Data.Entities.Comment", b =>
                {
                    b.HasOne("GameStore.Data.Entities.Game", "Game")
                        .WithMany("Comments")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStore.Data.Entities.Comment", null)
                        .WithMany("Replies")
                        .HasForeignKey("ParentId");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("GameStore.Data.Entities.Game", b =>
                {
                    b.HasOne("GameStore.Data.Entities.Publisher", "Publisher")
                        .WithMany("Games")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("GameStore.Data.Entities.GameGenre", b =>
                {
                    b.HasOne("GameStore.Data.Entities.Game", "Game")
                        .WithMany("GameGenres")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStore.Data.Entities.Genre", "Genre")
                        .WithMany("GenreGames")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("GameStore.Data.Entities.GamePlatform", b =>
                {
                    b.HasOne("GameStore.Data.Entities.Game", "Game")
                        .WithMany("GamePlatforms")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStore.Data.Entities.Platform", "Platform")
                        .WithMany("PlatformGames")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("GameStore.Data.Entities.Genre", b =>
                {
                    b.HasOne("GameStore.Data.Entities.Genre", null)
                        .WithMany("SubGenres")
                        .HasForeignKey("ParentGenreId");
                });

            modelBuilder.Entity("GameStore.Data.Entities.Identity.ApplicationUserRole", b =>
                {
                    b.HasOne("GameStore.Data.Entities.Identity.ApplicationRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStore.Data.Entities.Identity.ApplicationUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GameStore.Data.Entities.Order", b =>
                {
                    b.HasOne("GameStore.Data.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("GameStore.Data.Entities.OrderDetail", b =>
                {
                    b.HasOne("GameStore.Data.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameStore.Data.Entities.Game", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("GameStore.Data.Entities.Publisher", b =>
                {
                    b.HasOne("GameStore.Data.Entities.Identity.ApplicationUser", null)
                        .WithOne()
                        .HasForeignKey("GameStore.Data.Entities.Publisher", "AccountId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("GameStore.Data.Entities.Identity.ApplicationRole", null)
                        .WithMany("RoleClaims")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("GameStore.Data.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("GameStore.Data.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("GameStore.Data.Entities.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameStore.Data.Entities.Comment", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("GameStore.Data.Entities.Game", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("GameGenres");

                    b.Navigation("GamePlatforms");
                });

            modelBuilder.Entity("GameStore.Data.Entities.Genre", b =>
                {
                    b.Navigation("GenreGames");

                    b.Navigation("SubGenres");
                });

            modelBuilder.Entity("GameStore.Data.Entities.Identity.ApplicationRole", b =>
                {
                    b.Navigation("RoleClaims");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("GameStore.Data.Entities.Identity.ApplicationUser", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("GameStore.Data.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("GameStore.Data.Entities.Platform", b =>
                {
                    b.Navigation("PlatformGames");
                });

            modelBuilder.Entity("GameStore.Data.Entities.Publisher", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
